name: Release Chart Stable
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release chart
      uses: helm/chart-releaser-action@v1.2.1
      with:
        chart_path: ./charts/my-chart
        release_name: my-chart-stable
        chart_version: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

---

name: Release Chart Beta
on:
  push:
    branches:
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release chart
      uses: helm/chart-releaser-action@v1.2.1
      with:
        chart_path: ./charts/my-chart
        release_name: my-chart-beta
        chart_version: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
