name: Verify Chart Version

on:
  # Triggers the workflow on push or pull request events but only for the "development" branch
#   push:
#     branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "verifyChartVersion"
  verifyChartVersion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Verify Chart Version
        run: |
        
          # Get the base commit SHA for the pull request
          base_commit=$(jq .pull_request.base.sha -r "$GITHUB_EVENT_PATH")
          
          # Get the version number from Chart.yaml in the base commit
          git fetch &> /dev/null
          previous_version=$(git show $base_commit:charts/volumez-csi/Chart.yaml | grep '^version:' | awk '{print $2}')
          echo "previous version:" $previous_version
          
          if [[ $previous_version == *"rc"* ]]; then
            # Increment the RC version
            rc_version=$(echo $previous_version | awk -F '-rc.' '{print $2}')
            new_rc_version=$(expr $rc_version + 1)
            new_version=$(echo $previous_version | sed "s/rc.$rc_version/rc.$new_rc_version/")
            echo "new version1:" $new_version
          else
            # Increment the minor version
            minor_version=$(echo $previous_version | awk -F '.' '{print $2}')
            echo "minor version:" $minor_version
            new_minor_version=$(expr $minor_version + 1)
            echo "new minor version:" $new_minor_version
            new_version=$(echo $previous_version | sed "s/.$minor_version./.$new_minor_version./")
            new_version="$new_version-rc.1"
            echo "new version2:" $new_version
          fi
          echo "new version3:" $new_version
          sed -i "s/version: $version/version: $new_version/" charts/volumez-csi/Chart.yaml
      
      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -a -m "Update file in pull request"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
